# Generated by Django 6.0.3 on 2026-03-27 00:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmokeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('camera_id', models.UUIDField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='smoke_events/%Y/%m/%d/')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('confidence', models.FloatField()),
                ('intensity', models.FloatField()),
            ],
            options={
                'db_table': 'smoke_events',
                'ordering': ['-detected_at'],
            },
        ),
    ]
