# Generated by Django 6.0.1 on 2026-02-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('is_admin', 'General Administrative Access'), ('can_add_user', 'Can add new user (Admin / Operator)')]},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('OPERATOR', 'Operator')], default='ADMIN', max_length=10),
        ),
    ]
