# Generated by Django 6.0.3 on 2026-04-25 20:31

import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_management_refactor'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.CustomUserManager()),
            ],
        ),
    ]
