# Generated by Django 4.2.8 on 2026-03-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='stream_url',
            field=models.URLField(unique=True),
        ),
    ]
