# Generated by Django 6.0.3 on 2026-03-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_alter_camera_stream_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('removed', 'Removed')], default='active', max_length=10),
        ),
        migrations.AlterModelTable(
            name='camera',
            table='cameras',
        ),
    ]
